### ISSUE TITLE
Update Dependencies: StyleLint 14.9.1

### ISSUE THREAD

**Issue by movahhedi** [ronilaukkarinen/gulp-stylelint#5]
The latest version of stylelint is 14.9.1. Since the goal is to be up to date, updating it will do well.
Thanks.

**Comment by movahhedi** [comment]
Any thoughts? The version is 14.14.1 now @ronilaukkarinen

**Comment by rollecode** [comment]
@movahhedi Thank you for the ping! I've been too busy and missed the first one. Going to update this soon. Pull requests always appreciated.

**Comment by movahhedi** [comment]
Just another notification to let you know that Stylelint's version is now 15.1.0 😊
@ronilaukkarinen

**Comment by rollecode** [comment]
> Just another notification to let you know that Stylelint's version is now 15.1.0 😊 @ronilaukkarinen

Thanks for the ping. Updated locally and ran some tests, encountered couple of errors. Will tackle these soon.

**Comment by rollecode** [comment]
@movahhedi https://github.com/ronilaukkarinen/gulp-stylelint/releases/tag/14.1.0
